# Generated by Django 3.1.2 on 2020-10-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entries',
            new_name='entrie',
        ),
    ]
